# Generated by Django 4.1.6 on 2023-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField(unique=True),
        ),
    ]
